/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateReminderDto,
  ReminderEntity,
  RemindersControllerFindAllParams,
  UpdateReminderDto
} from '../model';

import { customInstance } from '../../apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type remindersControllerCreateResponse201 = {
  data: ReminderEntity
  status: 201
}

export type remindersControllerCreateResponseSuccess = (remindersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type remindersControllerCreateResponse = (remindersControllerCreateResponseSuccess)

export const getRemindersControllerCreateUrl = () => {




  return `/api/reminders`
}

/**
 * @summary 리마인더 생성
 */
export const remindersControllerCreate = async (createReminderDto: CreateReminderDto, options?: RequestInit): Promise<remindersControllerCreateResponse> => {

  return customInstance<remindersControllerCreateResponse>(getRemindersControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReminderDto,)
  }
);}




export const getRemindersControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerCreate>>, TError,{data: CreateReminderDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof remindersControllerCreate>>, TError,{data: CreateReminderDto}, TContext> => {

const mutationKey = ['remindersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof remindersControllerCreate>>, {data: CreateReminderDto}> = (props) => {
          const {data} = props ?? {};

          return  remindersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemindersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof remindersControllerCreate>>>
    export type RemindersControllerCreateMutationBody = CreateReminderDto
    export type RemindersControllerCreateMutationError = unknown

    /**
 * @summary 리마인더 생성
 */
export const useRemindersControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerCreate>>, TError,{data: CreateReminderDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof remindersControllerCreate>>,
        TError,
        {data: CreateReminderDto},
        TContext
      > => {
      return useMutation(getRemindersControllerCreateMutationOptions(options), queryClient);
    }
    export type remindersControllerFindAllResponse200 = {
  data: ReminderEntity[]
  status: 200
}

export type remindersControllerFindAllResponseSuccess = (remindersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type remindersControllerFindAllResponse = (remindersControllerFindAllResponseSuccess)

export const getRemindersControllerFindAllUrl = (params?: RemindersControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reminders?${stringifiedParams}` : `/api/reminders`
}

/**
 * @summary 나의 리마인더 목록 조회 (Cursor 기반 페이지네이션)
 */
export const remindersControllerFindAll = async (params?: RemindersControllerFindAllParams, options?: RequestInit): Promise<remindersControllerFindAllResponse> => {

  return customInstance<remindersControllerFindAllResponse>(getRemindersControllerFindAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRemindersControllerFindAllQueryKey = (params?: RemindersControllerFindAllParams,) => {
    return [
    `/api/reminders`, ...(params ? [params] : [])
    ] as const;
    }


export const getRemindersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof remindersControllerFindAll>>, TError = unknown>(params?: RemindersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRemindersControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof remindersControllerFindAll>>> = ({ signal }) => remindersControllerFindAll(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RemindersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof remindersControllerFindAll>>>
export type RemindersControllerFindAllQueryError = unknown


export function useRemindersControllerFindAll<TData = Awaited<ReturnType<typeof remindersControllerFindAll>>, TError = unknown>(
 params: undefined |  RemindersControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof remindersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof remindersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemindersControllerFindAll<TData = Awaited<ReturnType<typeof remindersControllerFindAll>>, TError = unknown>(
 params?: RemindersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof remindersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof remindersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemindersControllerFindAll<TData = Awaited<ReturnType<typeof remindersControllerFindAll>>, TError = unknown>(
 params?: RemindersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 나의 리마인더 목록 조회 (Cursor 기반 페이지네이션)
 */

export function useRemindersControllerFindAll<TData = Awaited<ReturnType<typeof remindersControllerFindAll>>, TError = unknown>(
 params?: RemindersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRemindersControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type remindersControllerFindOneResponse200 = {
  data: ReminderEntity
  status: 200
}

export type remindersControllerFindOneResponseSuccess = (remindersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type remindersControllerFindOneResponse = (remindersControllerFindOneResponseSuccess)

export const getRemindersControllerFindOneUrl = (id: number,) => {




  return `/api/reminders/${id}`
}

/**
 * @summary 리마인더 상세 조회
 */
export const remindersControllerFindOne = async (id: number, options?: RequestInit): Promise<remindersControllerFindOneResponse> => {

  return customInstance<remindersControllerFindOneResponse>(getRemindersControllerFindOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRemindersControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/reminders/${id}`
    ] as const;
    }


export const getRemindersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof remindersControllerFindOne>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRemindersControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof remindersControllerFindOne>>> = ({ signal }) => remindersControllerFindOne(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RemindersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof remindersControllerFindOne>>>
export type RemindersControllerFindOneQueryError = unknown


export function useRemindersControllerFindOne<TData = Awaited<ReturnType<typeof remindersControllerFindOne>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof remindersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof remindersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemindersControllerFindOne<TData = Awaited<ReturnType<typeof remindersControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof remindersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof remindersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemindersControllerFindOne<TData = Awaited<ReturnType<typeof remindersControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 리마인더 상세 조회
 */

export function useRemindersControllerFindOne<TData = Awaited<ReturnType<typeof remindersControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof remindersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRemindersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type remindersControllerUpdateResponse200 = {
  data: ReminderEntity
  status: 200
}

export type remindersControllerUpdateResponseSuccess = (remindersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type remindersControllerUpdateResponse = (remindersControllerUpdateResponseSuccess)

export const getRemindersControllerUpdateUrl = (id: number,) => {




  return `/api/reminders/${id}`
}

/**
 * @summary 리마인더 수정
 */
export const remindersControllerUpdate = async (id: number,
    updateReminderDto: UpdateReminderDto, options?: RequestInit): Promise<remindersControllerUpdateResponse> => {

  return customInstance<remindersControllerUpdateResponse>(getRemindersControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReminderDto,)
  }
);}




export const getRemindersControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerUpdate>>, TError,{id: number;data: UpdateReminderDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof remindersControllerUpdate>>, TError,{id: number;data: UpdateReminderDto}, TContext> => {

const mutationKey = ['remindersControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof remindersControllerUpdate>>, {id: number;data: UpdateReminderDto}> = (props) => {
          const {id,data} = props ?? {};

          return  remindersControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemindersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof remindersControllerUpdate>>>
    export type RemindersControllerUpdateMutationBody = UpdateReminderDto
    export type RemindersControllerUpdateMutationError = unknown

    /**
 * @summary 리마인더 수정
 */
export const useRemindersControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerUpdate>>, TError,{id: number;data: UpdateReminderDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof remindersControllerUpdate>>,
        TError,
        {id: number;data: UpdateReminderDto},
        TContext
      > => {
      return useMutation(getRemindersControllerUpdateMutationOptions(options), queryClient);
    }
    export type remindersControllerRemoveResponse200 = {
  data: ReminderEntity
  status: 200
}

export type remindersControllerRemoveResponseSuccess = (remindersControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type remindersControllerRemoveResponse = (remindersControllerRemoveResponseSuccess)

export const getRemindersControllerRemoveUrl = (id: number,) => {




  return `/api/reminders/${id}`
}

/**
 * @summary 리마인더 삭제
 */
export const remindersControllerRemove = async (id: number, options?: RequestInit): Promise<remindersControllerRemoveResponse> => {

  return customInstance<remindersControllerRemoveResponse>(getRemindersControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemindersControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof remindersControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['remindersControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof remindersControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  remindersControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemindersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof remindersControllerRemove>>>

    export type RemindersControllerRemoveMutationError = unknown

    /**
 * @summary 리마인더 삭제
 */
export const useRemindersControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof remindersControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof remindersControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getRemindersControllerRemoveMutationOptions(options), queryClient);
    }
