/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 사용자 이메일 주소 */
  email: string;
  /** 비밀번호 */
  password: string;
}
