/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export type RemindersControllerFindAllParams = {
/**
 * 가져올 데이터의 최대 개수 (기본값: 20)
 * @minimum 1
 */
take?: number;
/**
 * 마지막으로 조회한 데이터의 ID (Cursor)
 */
cursor?: number;
/**
 * 특정 섹션으로 필터링
 */
sectionId?: string;
};
