/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export type RemindersControllerFindAllParams = {
/**
 * 섹션별 필터링
 */
sectionId?: string;
};
