/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSectionDto,
  SectionEntity,
  UpdateSectionDto
} from '../model';

import { customInstance } from '../../apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type sectionsControllerCreateResponse201 = {
  data: SectionEntity
  status: 201
}

export type sectionsControllerCreateResponseSuccess = (sectionsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type sectionsControllerCreateResponse = (sectionsControllerCreateResponseSuccess)

export const getSectionsControllerCreateUrl = () => {




  return `/api/sections`
}

/**
 * 현재 사용자에게 새 섹션을 생성합니다.
 * @summary 섹션 생성
 */
export const sectionsControllerCreate = async (createSectionDto: CreateSectionDto, options?: RequestInit): Promise<sectionsControllerCreateResponse> => {

  return customInstance<sectionsControllerCreateResponse>(getSectionsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSectionDto,)
  }
);}




export const getSectionsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext> => {

const mutationKey = ['sectionsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerCreate>>, {data: CreateSectionDto}> = (props) => {
          const {data} = props ?? {};

          return  sectionsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerCreate>>>
    export type SectionsControllerCreateMutationBody = CreateSectionDto
    export type SectionsControllerCreateMutationError = unknown

    /**
 * @summary 섹션 생성
 */
export const useSectionsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerCreate>>, TError,{data: CreateSectionDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerCreate>>,
        TError,
        {data: CreateSectionDto},
        TContext
      > => {
      return useMutation(getSectionsControllerCreateMutationOptions(options), queryClient);
    }
    export type sectionsControllerFindAllResponse200 = {
  data: SectionEntity[]
  status: 200
}

export type sectionsControllerFindAllResponseSuccess = (sectionsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type sectionsControllerFindAllResponse = (sectionsControllerFindAllResponseSuccess)

export const getSectionsControllerFindAllUrl = () => {




  return `/api/sections`
}

/**
 * 삭제되지 않은 현재 사용자의 섹션을 생성일 오름차순으로 조회합니다.
 * @summary 나의 모든 섹션 조회
 */
export const sectionsControllerFindAll = async ( options?: RequestInit): Promise<sectionsControllerFindAllResponse> => {

  return customInstance<sectionsControllerFindAllResponse>(getSectionsControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSectionsControllerFindAllQueryKey = () => {
    return [
    `/api/sections`
    ] as const;
    }


export const getSectionsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectionsControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectionsControllerFindAll>>> = ({ signal }) => sectionsControllerFindAll({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectionsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerFindAll>>>
export type SectionsControllerFindAllQueryError = unknown


export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 나의 모든 섹션 조회
 */

export function useSectionsControllerFindAll<TData = Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectionsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type sectionsControllerFindOneResponse200 = {
  data: SectionEntity
  status: 200
}

export type sectionsControllerFindOneResponseSuccess = (sectionsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type sectionsControllerFindOneResponse = (sectionsControllerFindOneResponseSuccess)

export const getSectionsControllerFindOneUrl = (id: string,) => {




  return `/api/sections/${id}`
}

/**
 * 삭제되지 않았고 현재 사용자가 소유한 섹션을 조회합니다.
 * @summary 특정 섹션 상세 조회
 */
export const sectionsControllerFindOne = async (id: string, options?: RequestInit): Promise<sectionsControllerFindOneResponse> => {

  return customInstance<sectionsControllerFindOneResponse>(getSectionsControllerFindOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSectionsControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/sections/${id}`
    ] as const;
    }


export const getSectionsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectionsControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectionsControllerFindOne>>> = ({ signal }) => sectionsControllerFindOne(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectionsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerFindOne>>>
export type SectionsControllerFindOneQueryError = unknown


export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sectionsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 섹션 상세 조회
 */

export function useSectionsControllerFindOne<TData = Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectionsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectionsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type sectionsControllerUpdateResponse200 = {
  data: SectionEntity
  status: 200
}

export type sectionsControllerUpdateResponseSuccess = (sectionsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type sectionsControllerUpdateResponse = (sectionsControllerUpdateResponseSuccess)

export const getSectionsControllerUpdateUrl = (id: string,) => {




  return `/api/sections/${id}`
}

/**
 * 고정 섹션이 아닌 현재 사용자의 섹션 제목을 수정합니다.
 * @summary 섹션 수정
 */
export const sectionsControllerUpdate = async (id: string,
    updateSectionDto: UpdateSectionDto, options?: RequestInit): Promise<sectionsControllerUpdateResponse> => {

  return customInstance<sectionsControllerUpdateResponse>(getSectionsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSectionDto,)
  }
);}




export const getSectionsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext> => {

const mutationKey = ['sectionsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerUpdate>>, {id: string;data: UpdateSectionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  sectionsControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerUpdate>>>
    export type SectionsControllerUpdateMutationBody = UpdateSectionDto
    export type SectionsControllerUpdateMutationError = unknown

    /**
 * @summary 섹션 수정
 */
export const useSectionsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerUpdate>>, TError,{id: string;data: UpdateSectionDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerUpdate>>,
        TError,
        {id: string;data: UpdateSectionDto},
        TContext
      > => {
      return useMutation(getSectionsControllerUpdateMutationOptions(options), queryClient);
    }
    export type sectionsControllerRemoveResponse200 = {
  data: SectionEntity
  status: 200
}

export type sectionsControllerRemoveResponseSuccess = (sectionsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type sectionsControllerRemoveResponse = (sectionsControllerRemoveResponseSuccess)

export const getSectionsControllerRemoveUrl = (id: string,) => {




  return `/api/sections/${id}`
}

/**
 * 고정 섹션이 아닌 현재 사용자의 섹션과 그 안의 리마인더를 함께 소프트 삭제합니다.
 * @summary 섹션 삭제
 */
export const sectionsControllerRemove = async (id: string, options?: RequestInit): Promise<sectionsControllerRemoveResponse> => {

  return customInstance<sectionsControllerRemoveResponse>(getSectionsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getSectionsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['sectionsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sectionsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  sectionsControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SectionsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof sectionsControllerRemove>>>

    export type SectionsControllerRemoveMutationError = unknown

    /**
 * @summary 섹션 삭제
 */
export const useSectionsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sectionsControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sectionsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSectionsControllerRemoveMutationOptions(options), queryClient);
    }
