/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { SyncReminderChangesEntity } from './syncReminderChangesEntity';
import type { SyncSectionChangesEntity } from './syncSectionChangesEntity';

export interface PullSyncResponseEntity {
  /** 서버 기준 현재 시각. 클라이언트는 동기화 성공 후 이 값을 저장합니다. */
  serverTime: string;
  sections: SyncSectionChangesEntity;
  reminders: SyncReminderChangesEntity;
}
