/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** 사용자 이메일 주소 */
  email: string;
  /**
     * 비밀번호 (영문, 숫자, 특수문자 포함 최소 8자)
     * @minLength 8
     * @pattern ^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$
     */
  password: string;
}
