/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export type SyncControllerPullParams = {
/**
 * 마지막으로 성공한 동기화 시각. 생략하면 삭제되지 않은 전체 데이터를 반환합니다.
 */
since?: string;
};
