/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface UpdateSectionDto {
  /**
     * 섹션 제목. 최대 50자까지 입력할 수 있습니다.
     * @maxLength 50
     */
  title?: string;
}
