/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface UserEntity {
  /** 사용자 고유 ID */
  id: number;
  /** 사용자 이메일 */
  email: string;
  /** 가입 경로 (local, google 등) */
  provider: string;
  /**
     * 소셜 로그인 고유 ID
     * @nullable
     */
  socialId?: string | null;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  updatedAt: string;
}
