/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Tickit Server API
 * Tickit 클라우드 서버 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PullSyncResponseEntity,
  SyncControllerPullParams
} from '../model';

import { customInstance } from '../../apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type syncControllerPullResponse200 = {
  data: PullSyncResponseEntity
  status: 200
}

export type syncControllerPullResponseSuccess = (syncControllerPullResponse200) & {
  headers: Headers;
};
;

export type syncControllerPullResponse = (syncControllerPullResponseSuccess)

export const getSyncControllerPullUrl = (params?: SyncControllerPullParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sync?${stringifiedParams}` : `/api/sync`
}

/**
 * 마지막 동기화 시각 이후 서버에서 변경되거나 삭제된 섹션과 리마인더를 조회합니다.
 * @summary Pull Sync
 */
export const syncControllerPull = async (params?: SyncControllerPullParams, options?: RequestInit): Promise<syncControllerPullResponse> => {

  return customInstance<syncControllerPullResponse>(getSyncControllerPullUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSyncControllerPullQueryKey = (params?: SyncControllerPullParams,) => {
    return [
    `/api/sync`, ...(params ? [params] : [])
    ] as const;
    }


export const getSyncControllerPullQueryOptions = <TData = Awaited<ReturnType<typeof syncControllerPull>>, TError = unknown>(params?: SyncControllerPullParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSyncControllerPullQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof syncControllerPull>>> = ({ signal }) => syncControllerPull(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SyncControllerPullQueryResult = NonNullable<Awaited<ReturnType<typeof syncControllerPull>>>
export type SyncControllerPullQueryError = unknown


export function useSyncControllerPull<TData = Awaited<ReturnType<typeof syncControllerPull>>, TError = unknown>(
 params: undefined |  SyncControllerPullParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof syncControllerPull>>,
          TError,
          Awaited<ReturnType<typeof syncControllerPull>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSyncControllerPull<TData = Awaited<ReturnType<typeof syncControllerPull>>, TError = unknown>(
 params?: SyncControllerPullParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof syncControllerPull>>,
          TError,
          Awaited<ReturnType<typeof syncControllerPull>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSyncControllerPull<TData = Awaited<ReturnType<typeof syncControllerPull>>, TError = unknown>(
 params?: SyncControllerPullParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Pull Sync
 */

export function useSyncControllerPull<TData = Awaited<ReturnType<typeof syncControllerPull>>, TError = unknown>(
 params?: SyncControllerPullParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof syncControllerPull>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSyncControllerPullQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






